<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40" 
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" 
                xmlns:xhtml="http://www.w3.org/1999/xhtml" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap | Autos Rental</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&amp;display=swap" rel="stylesheet" />
        <style type="text/css">
          body {
            font-family: 'Inter', sans-serif;
            font-size: 14px;
            color: #e2e8f0;
            background-color: #0f172a;
            margin: 0;
            padding: 40px 20px;
            line-height: 1.5;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: rgba(30, 41, 59, 0.5);
            backdrop-filter: blur(12px);
            -webkit-backdrop-filter: blur(12px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 16px;
            padding: 40px;
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
          }
          h1 {
            font-weight: 600;
            font-size: 28px;
            margin: 0 0 10px 0;
            background: linear-gradient(to right, #60a5fa, #a78bfa);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
          }
          p.description {
            color: #94a3b8;
            margin-bottom: 30px;
            font-size: 16px;
          }
          table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0;
            margin-top: 20px;
          }
          th {
            text-align: left;
            padding: 12px 16px;
            background: rgba(255, 255, 255, 0.05);
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            color: #f8fafc;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 12px;
            letter-spacing: 0.05em;
          }
          th:first-child { border-top-left-radius: 8px; }
          th:last-child { border-top-right-radius: 8px; }
          td {
            padding: 12px 16px;
            border-bottom: 1px solid rgba(255, 255, 255, 0.05);
            word-break: break-all;
          }
          tr:last-child td { border-bottom: none; }
          tr:hover td {
            background: rgba(255, 255, 255, 0.02);
          }
          a {
            color: #60a5fa;
            text-decoration: none;
            transition: color 0.2s;
          }
          a:hover {
            color: #93c5fd;
            text-decoration: underline;
          }
          .alternates {
            display: flex;
            gap: 8px;
            flex-wrap: wrap;
          }
          .lang-badge {
            font-size: 10px;
            padding: 2px 6px;
            background: rgba(255, 255, 255, 0.1);
            border-radius: 4px;
            color: #94a3b8;
            border: 1px solid rgba(255, 255, 255, 0.05);
          }
          .count {
            display: inline-block;
            background: #3b82f6;
            color: white;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 12px;
            margin-left: 10px;
            vertical-align: middle;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>XML Sitemap <span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs</span></h1>
          <p class="description">
            This is an XML Sitemap generated by Autos Rental, intended for consumption by search engines.
          </p>
          
          <table>
            <thead>
              <tr>
                <th width="45%">URL Path</th>
                <th width="15%">Last Modified</th>
                <th width="10%">Priority</th>
                <th width="15%">Frequency</th>
                <th width="15%">Alternates</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <xsl:sort select="sitemap:lastmod" order="descending"/>
                <tr>
                  <td>
                    <a href="{sitemap:loc}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td>
                    <xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), ' ', substring(sitemap:lastmod, 12, 5))"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:priority"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:changefreq"/>
                  </td>
                  <td>
                    <div class="alternates">
                      <xsl:for-each select="xhtml:link">
                        <span class="lang-badge">
                          <xsl:value-of select="@hreflang"/>
                        </span>
                      </xsl:for-each>
                    </div>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
